import '../core/services/app_config.dart';

class AppLocalizations {
  final String locale;
  AppLocalizations(this.locale);

  String tr(String key) {
    return _allStrings[locale]?[key] ?? _allStrings['fr']?[key] ?? key;
  }

  static Map<String, Map<String, String>> _allStrings = {
    'fr': _fr,
    'en': _en,
  };

  static Map<String, String> _fr = {
    'app.title': 'Ontik',
    'app.loading': 'Chargement...',

    'splash.title': 'Ontik',

    'auth.login.title': 'Connexion',
    'auth.login.email': 'Email',
    'auth.login.password': 'Mot de passe',
    'auth.login.submit': 'Se connecter',
    'auth.login.forgotPassword': 'Mot de passe oublié ?',
    'auth.login.noAccount': "Pas encore de compte ?",
    'auth.login.register': "S'inscrire",
    'auth.login.welcome': 'Bon retour',

    'auth.register.title': 'Inscription',
    'auth.register.submit': "S'inscrire",
    'auth.register.haveAccount': 'Déjà un compte ?',
    'auth.register.login': 'Se connecter',

    'auth.forgotPassword.title': 'Mot de passe oublié',
    'auth.register.success': 'Inscription réussie. Connectez-vous.',

    'client.home': 'Événements',
    'client.tickets': 'Mes billets',
    'client.account': 'Compte',
    'client.profile.title': 'Mon Profil',
    'client.layout.title': 'Ontik',
    'client.home.filters': 'Filtres',
    'client.home.reset': 'Réinitialiser',
    'client.home.status': 'Statut',
    'client.home.venue': 'Lieu',
    'client.home.allVenues': 'Tous les lieux',
    'client.home.selectDateRange': 'Sélectionner une plage',
    'client.home.apply': 'Appliquer',
    'client.home.searchHint': 'Rechercher un événement...',
    'client.home.featured': 'Événements à la une',
    'client.home.noEvents': 'Aucun événement trouvé',
    'client.home.venueNotSpecified': 'Lieu non spécifié',
    'client.home.priceUnavailable': 'Prix non disponible',
    'client.home.standard': 'Standard',
    'client.home.promoTitle': '-20% sur votre premier billet',
    'client.home.promoSubtitle': 'Utilisez le code SECURE20 lors du paiement.',
    'client.home.retry': 'Réessayer',
    'client.homeDetail.share': 'Partager',
    'client.homeDetail.retry': 'Réessayer',
    'client.homeDetail.eventNotFound': 'Événement non trouvé',
    'client.homeDetail.event': 'ÉVÉNEMENT',
    'client.homeDetail.date': 'Date',
    'client.homeDetail.time': 'Heure',
    'client.homeDetail.venueNotSpecified': 'Lieu non spécifié',
    'client.homeDetail.about': 'À propos de l\'événement',
    'client.homeDetail.noDescription': 'Aucune description disponible.',
    'client.homeDetail.characteristic': 'Caractéristique',
    'client.homeDetail.availableZones': 'Zones disponibles',
    'client.homeDetail.unlimitedSeats': 'Places illimitées',
    'client.homeDetail.placesAvailable': 'places disponibles',
    'client.homeDetail.priceUnavailable': 'Prix non disponible',
    'client.homeDetail.from': 'À partir de',
    'client.homeDetail.book': 'RÉSERVER MA PLACE',
    'client.profile.myReservations': 'Mes Réservations',
    'client.profile.reservationsTab': 'Réservations',
    'client.profile.ticketsTab': 'Billets',
    'client.profile.referenceCodes': 'Codes de référence',
    'client.profile.noReservations': 'Aucune réservation',
    'client.profile.reservationsWillAppear': 'Vos réservations apparaîtront ici.',
    'client.profile.unknownDate': 'Date inconnue',
    'client.profile.reservationReference': 'Référence réservation',
    'client.profile.noTickets': 'Aucun billet',
    'client.profile.ticketsWillAppear': 'Vos billets apparaîtront ici après réservation.',
    'client.profile.event': 'Événement',
    'client.profile.room': 'Salle',
    'client.profile.row': 'Rang',
    'client.profile.seat': 'Place',
    'client.profile.reference': 'Référence',
    'client.profile.expired': 'EXPIRÉ',
    'client.profile.reservation': 'Réservation',
    'client.profile.ticketsCount': 'billet(s)',
    'client.profile.personalInfo': 'Informations personnelles',
    'client.profile.lastName': 'Nom',
    'client.profile.firstName': 'Prénoms',
    'client.profile.phone': 'Téléphone',
    'client.profile.confirm': 'Confirmer',
    'client.profile.confirmSave': 'Voulez-vous enregistrer les modifications ?',
    'client.profile.updated': 'Informations mises à jour',
    'client.profile.paymentMethods': 'Moyens de paiement',
    'client.profile.paymentHistoryComing': 'Historique des paiements - fonctionnalité à venir.',
    'client.profile.close': 'Fermer',
    'client.profile.confirmLogout': 'Voulez-vous vraiment vous déconnecter ?',
    'client.profile.user': 'Utilisateur',
    'client.profile.favorites': 'Favoris',
    'client.profile.alerts': 'Alertes',
    'client.profile.accountGroup': 'Compte',
    'client.profile.securityGroup': 'Sécurité',
    'client.profile.password2FA': 'Mot de passe & 2FA',
    'client.profile.secure': 'Sécurisé',
    'client.profile.connectedDevices': 'Appareils connectés',
    'client.reservation.share': 'Partager',
    'client.reservation.eventNotFound': 'Événement non trouvé',
    'client.reservation.noSeatsAvailable': 'Aucune place disponible',
    'client.reservation.stage': 'SCÈNE / STAGE',
    'client.reservation.selectBlock': 'Sélectionnez un bloc pour voir les places disponibles',
    'client.reservation.noSeatsInBlock': 'Aucune place disponible dans ce bloc',
    'client.reservation.blockView': 'Vue depuis le bloc',
    'client.reservation.noStandingZones': 'Aucune zone debout disponible',
    'client.reservation.standingZones': 'Zones debout',
    'client.reservation.unlimitedSeats': 'Places illimitées',
    'client.reservation.selectedSeats': 'PLACES SÉLECTIONNÉES',
    'client.reservation.confirmSelection': 'Confirmer la sélection',
    'client.reservation.selectInBlock': 'Sélectionnez vos places dans le bloc',
    'client.reservation.places': 'places',
    'client.reservation.remainingSeats': 'place(s) restante(s) sur',
    'client.reservation.tickets': 'billet(s)',
    'client.reservation.estimatedTotal': 'TOTAL ESTIMÉ',
    'client.payment.processing': 'Traitement du paiement...',
    'client.payment.paymentMethod': 'Mode de paiement',
    'client.payment.summary': 'Récapitulatif',
    'client.payment.venue': 'SALLE',
    'client.payment.event': 'Événement',
    'client.payment.price': 'PRIX',
    'client.payment.row': 'RANG',
    'client.payment.seat': 'PLACE',
    'client.payment.tickets': 'BILLETS',
    'client.payment.orderVerified': 'Commande vérifiée',
    'client.payment.card': 'Carte Bancaire',
    'client.payment.cardSubtitle': 'Visa, Mastercard, AMEX',
    'client.payment.mvolaSubtitle': 'Paiement mobile MVola',
    'client.payment.orangeSubtitle': 'Paiement mobile Orange',
    'client.payment.airtelSubtitle': 'Paiement mobile Airtel',
    'client.payment.transactionRef': 'Référence de transaction',
    'client.payment.phoneNumber': 'Numéro de téléphone',
    'client.payment.fullName': 'Nom complet',
    'client.payment.securityDisclaimer': 'Vos données de paiement sont cryptées de bout en bout. Nous sommes certifiés PCI-DSS Level 1.',
    'client.payment.errorTransactionRef': 'La référence de transaction est requise',
    'client.payment.errorPhoneNumber': 'Le numéro de téléphone est requis',
    'client.payment.errorCardInfo': 'Les informations de carte sont requises',
    'client.payment.errorNotLoggedIn': 'Utilisateur non connecté',
    'client.payment.success': 'Réservation réussie !',
    'client.payment.errorTimeout': 'Le serveur ne répond pas. Vérifiez votre connexion.',
    'client.payment.errorSeatTaken': 'Place déjà réservée ou indisponible. Veuillez réessayer.',
    'client.payment.errorInsufficientFunds': 'Fonds insuffisants pour effectuer cette transaction.',
    'client.payment.errorPromoCode': 'Code promo invalide ou expiré.',
    'client.payment.successReduction': 'Réservation réussie ! Réduction de',
    'client.payment.pay': 'Payer',
    'client.ticket.title': 'Billet',
    'client.ticket.notFound': 'Billet non trouvé',
    'client.ticket.valid': 'VALIDE',
    'client.ticket.invalid': 'INVALIDE',
    'client.ticket.downloadPDF': 'Télécharger PDF',
    'client.ticket.event': 'Événement',
    'client.ticket.seat': 'Place',
    'client.ticket.row': 'Rangée',
    'client.ticket.type': 'Type',
    'client.ticket.zone': 'Zone',
    'client.ticket.price': 'Prix',
    'client.ticket.holder': 'Titulaire',
    'client.ticket.noTickets': 'Aucun billet',
    'client.ticket.afterPurchase': 'Vos billets apparaîtront ici après achat.',
    'client.ticket.myTickets': 'Mes Tickets',
    'client.ticket.manageTickets': 'Gérez vos accès et vos réservations',
    'client.ticket.room': 'Salle',
    'client.ticket.pdfSaved': 'PDF enregistré dans',
    'client.ticket.downloadFailed': 'Échec du téléchargement :',
    'client.ticket.reference': 'Référence',
    'client.ticket.expired': 'EXPIRÉ',

    'organizer.dashboard': 'Dashboard',
    'organizer.events': 'Événements',
    'organizer.tickets': 'Tickets',
    'organizer.reservations': 'Réservations',
    'organizer.account': 'Compte',
    'organizer.layout.title': 'Ontik - Organisateur',
    'organizer.profile.title': 'Profil',
    'organizer.overview': 'Aperçu',
    'organizer.events_active': '{count} événements actifs',
    'organizer.manage': 'Gérer',
    'organizer.revenue': 'Recettes',
    'organizer.fill_rate': 'Remplissage',
    'organizer.tickets_sold': 'Billets vendus',
    'organizer.seats_available': 'Places dispo.',
    'organizer.my_events': 'Mes événements',
    'organizer.see_all': 'Tout voir',
    'organizer.sales_evolution': 'Évolution des ventes',
    'organizer.top_events': 'Top événements',
    'organizer.suspend_event_title': 'Suspendre l\'événement',
    'organizer.suspend_confirm': 'Suspendre "{event}" ? Les réservations existantes seront conservées.',
    'organizer.suspend': 'Suspendre',
    'organizer.event_suspended': 'Événement suspendu',
    'organizer.event_resumed': 'Événement réactivé',
    'organizer.cancel_event_title': 'Annuler l\'événement',
    'organizer.cancel_confirm': 'Êtes-vous sûr d\'annuler "{event}" ?',
    'organizer.cancel_notify': 'Les clients réservés seront notifiés.',
    'organizer.cancel_reason': 'Motif d\'annulation',
    'organizer.cancel_event': 'Annuler l\'événement',
    'organizer.event_cancelled': 'Événement annulé',
    'organizer.info': 'Info',
    'organizer.reactivate': 'Réactiver',
    'organizer.no_events': 'Aucun événement',
    'organizer.create_event': 'Créer un événement',
    'organizer.status_label': 'Statut',
    'organizer.date_label': 'Date',
    'organizer.time_label': 'Heure',
    'organizer.countdown_label': 'Compte à rebours',
    'organizer.description_label': 'Description',
    'organizer.category_label': 'Catégorie',
    'organizer.location_label': 'Lieu',
    'organizer.organizer_label': 'Organisateur',
    'organizer.features_label': 'Caractéristiques',
    'organizer.feature': 'Caractéristique',
    'organizer.ended_min': 'Terminé il y a {count} min',
    'organizer.ended_h': 'Terminé il y a {count}h',
    'organizer.ended_d': 'Terminé il y a {count}j',
    'organizer.ended_months': 'Terminé il y a {count} mois',
    'organizer.ended_years': 'Terminé il y a {count} an(s)',
    'organizer.starts_min': 'Commence dans {count} min',
    'organizer.starts_h': 'Commence dans {count}h',
    'organizer.starts_d': 'Commence dans {count}j',
    'organizer.personal_info': 'Informations personnelles',
    'organizer.last_name': 'Nom',
    'organizer.first_name': 'Prénoms',
    'organizer.phone': 'Téléphone',
    'organizer.save_changes_confirm': 'Voulez-vous enregistrer les modifications ?',
    'organizer.profile_updated': 'Profil mis à jour',
    'organizer.total_revenue': 'Revenu total',
    'organizer.load_error': 'Erreur de chargement',
    'organizer.latest_sales': 'Dernières ventes',
    'organizer.logout_confirm': 'Voulez-vous vraiment vous déconnecter ?',
    'organizer.org_code_missing': 'Code organisateur introuvable. Reconnectez-vous.',
    'organizer.today': 'Aujourd\'hui',
    'organizer.last_7_days': '7 jours',
    'organizer.last_30_days': '30 jours',
    'organizer.search_client': 'Rechercher un client...',
    'organizer.paid': 'Payé',
    'organizer.pending': 'En attente',
    'organizer.cancelled': 'Annulé',
    'organizer.reservation_count': '{count} réservation(s)',
    'organizer.no_reservations_for_event': 'Aucune réservation pour cet événement',
    'organizer.select_event': 'Sélectionnez un événement',
    'organizer.no_reservations': 'Aucune réservation',
    'organizer.ticket_count': '{count} billet(s)',
    'organizer.full_detail': 'Détail complet',
    'organizer.view_event': 'Voir événement',
    'organizer.available': 'Disponible',
    'organizer.scanned': 'Scanné',
    'organizer.pending_short': 'En att.',
    'organizer.pricing_title': 'Tarifs - {title}',
    'organizer.room_label': 'Salle:',
    'organizer.price_by_type': 'Prix par type de place',
    'organizer.price_by_type_desc': 'Définissez le prix pour chaque type de place. Toutes les places de ce type seront mises à jour.',
    'organizer.price': 'Prix',
    'organizer.apply': 'Appliquer',
    'organizer.type_assignment': 'Affectation des types',
    'organizer.type_assignment_desc': 'Sélectionnez les rangées ou places et assignez-leur un type.',
    'organizer.type_to_assign': 'Type à assigner',
    'organizer.new_type': '+ Nouveau type...',
    'organizer.assign': 'Affecter',
    'organizer.selection_count': '{rows} rangée(s) • {seats} place(s) sélectionnée(s)',
    'organizer.no_rows': 'Aucune rangée disponible',
    'organizer.click_seat_to_select': 'Cliquez sur une place dans la grille ci-dessous pour la sélectionner',
    'organizer.row_pricing': 'Tarification par rangée',
    'organizer.row_pricing_desc': 'Configurer le type et le prix pour chaque rangée.',
    'organizer.seat_grid': 'Grille individuelle',
    'organizer.search_seat': 'Rechercher place...',
    'organizer.type': 'Type',
    'organizer.seat_count_label': '{total} places • {configured} configurées',
    'organizer.configured': 'configuré',
    'organizer.price_with_currency': 'Prix ({currency})',
    'organizer.new_type_name': 'Nouveau type',
    'organizer.confirm_refund': 'Confirmer le remboursement',
    'organizer.refunds_title': 'Remboursements et annulations',
    'organizer.cancelled_badge': 'ANNULÉ',
    'organizer.refund_action': 'Rembourser',
    'organizer.data_export': 'Export des données',
    'organizer.select_event_export': 'Sélectionnez un événement pour exporter les données',
    'organizer.tickets_csv': 'Billets CSV',
    'organizer.reservations_csv': 'Réserv. CSV',
    'organizer.scan_ticket': 'Scanner un billet',
    'organizer.scan_next': 'Scanner suivant',
    'organizer.align_qr': 'Alignez le code QR dans le cadre',
    'organizer.ticket_valid': 'Billet valide',
    'organizer.ticket_invalid': 'Billet invalide',
    'organizer.step_infos': 'Infos',
    'organizer.step_date_time': 'Date & Heure',
    'organizer.step_location': 'Lieu & Places',
    'organizer.step_summary': 'Récapitulatif',
    'organizer.edit_event': 'Modifier l\'événement',
    'organizer.cancel_edit': 'Annuler la modification ?',
    'organizer.cancel_create': 'Annuler la création ?',
    'organizer.unsaved_changes': 'Les modifications non enregistrées seront perdues.',
    'organizer.event_updated': 'Événement modifié',
    'organizer.event_created': 'Événement créé',
    'organizer.publish_event': 'Publier l\'événement',

    'organizer.status_suspended': 'Suspendu',
    'organizer.status_cancelled': 'Annulé',
    'organizer.status_upcoming': 'À venir',
    'organizer.status_in_progress': 'En cours',
    'organizer.status_ended': 'Terminé',
    'organizer.event_label': 'Événement',
    'organizer.period_today': 'Aujourd\'hui',
    'organizer.period_7days': '7 jours',
    'organizer.period_30days': '30 jours',
    'organizer.search_client_hint': 'Rechercher un client...',
    'organizer.status_paid': 'Payé',
    'organizer.status_pending': 'En attente',
    'organizer.status_cancelled_short': 'Annulé',
    'organizer.retry_button': 'Réessayer',
    'organizer.unknown_client': 'Inconnu',
    'organizer.tickets_count': '{count} billet(s)',
    'organizer.seat_place': 'Place {seat}',
    'organizer.full_detail_button': 'Détail complet',
    'organizer.view_event_button': 'Voir événement',
    'organizer.reservation_header': 'Réservation #{id}',
    'organizer.client_section': 'Client',
    'organizer.name_field': 'Nom',
    'organizer.code_field': 'Code',
    'organizer.email_field': 'Email',
    'organizer.phone_field': 'Téléphone',
    'organizer.payment_section': 'Paiement',
    'organizer.amount_field': 'Montant',
    'organizer.mode_field': 'Mode',
    'organizer.payment_date_field': 'Date',
    'organizer.status_field': 'Statut',
    'organizer.tickets_section': 'Billets',
    'organizer.no_tickets_text': 'Aucun billet',
    'organizer.seat_place_detail': 'Place {seat}',
    'organizer.row_detail': 'Rang {row}',
    'organizer.org_code_missing_reconnect': 'Code organisateur introuvable. Reconnectez-vous.',
    'organizer.paid_status': 'Payé',
    'organizer.pending_status': 'En attente',
    'organizer.available_status': 'Disponible',
    'organizer.scanned_status': 'Scanné',
    'organizer.unknown_status': 'Inconnu',
    'organizer.event_dropdown': 'Événement',
    'organizer.all_filter': 'Tous',
    'organizer.paid_filter': 'Payés',
    'organizer.pending_filter': 'En att.',
    'organizer.pricing_applied_row': 'Tarification appliquée au rang {row}',
    'organizer.pricing_applied_type': 'Prix appliqué au type {type}',
    'organizer.select_min_row_or_seat': 'Sélectionnez au moins une rangée ou une place',
    'organizer.type_assigned_msg': 'Type {type} assigné',
    'organizer.seat_updated_msg': 'Place {seat} mise à jour',
    'organizer.pricing_header': 'Tarifs - {title}',
    'organizer.room_selector': 'Salle:',
    'organizer.price_by_type_title': 'Prix par type de place',
    'organizer.price_field': 'Prix',
    'organizer.apply_button': 'Appliquer',
    'organizer.type_assignment_title': 'Affectation des types',
    'organizer.new_type_option': '+ Nouveau type...',
    'organizer.name_placeholder': 'Nom',
    'organizer.assign_button': 'Affecter',
    'organizer.no_rows_available': 'Aucune rangée disponible',
    'organizer.row_pricing_title': 'Tarification par rangée',
    'organizer.seat_grid_title': 'Grille individuelle',
    'organizer.search_seat_hint': 'Rechercher place...',
    'organizer.type_dropdown': 'Type',
    'organizer.all_option': 'Tous',
    'organizer.seat_count_configured': '{total} places • {configured} configurées',
    'organizer.seat_dialog_title': 'Place {seat}',
    'organizer.new_type_label': 'Nouveau type',
    'organizer.price_currency': 'Prix ({currency})',
    'organizer.cancel_button': 'Annuler',
    'organizer.save_button': 'Enregistrer',
    'organizer.row_title': 'Rangée {row}  ({count} places)',
    'organizer.configured_badge': 'configuré',
    'organizer.type_field': 'Type',
    'organizer.confirm_refund_title': 'Confirmer le remboursement',
    'organizer.confirm_refund_text': 'Voulez-vous annuler et rembourser la réservation #{id} ?',
    'organizer.cancel_refund_button': 'Annuler',
    'organizer.confirm_refund_button': 'Confirmer',
    'organizer.refund_result_message': 'Réservation #{id} annulée. Remboursement: {amount} {currency}',
    'organizer.cancelled_badge_label': 'ANNULÉ',
    'organizer.refund_action_button': 'Rembourser',
    'organizer.export_title': 'Export des données',
    'organizer.export_subtitle': 'Sélectionnez un événement pour exporter les données',
    'organizer.no_events_export': 'Aucun événement',
    'organizer.export_tickets_csv': 'Billets CSV',
    'organizer.export_reservations_csv': 'Réserv. CSV',
    'organizer.export_all_button': 'Tout',
    'organizer.export_saved_message': 'Fichier sauvegardé: {filename}',
    'organizer.export_error_prefix': 'Erreur: {message}',
    'organizer.scan_title': 'Scanner un billet',
    'organizer.scan_align_qr': 'Alignez le code QR dans le cadre',
    'organizer.scan_valid': 'Billet valide',
    'organizer.scan_invalid': 'Billet invalide',
    'organizer.scan_code_label': 'Code : {code}',
    'organizer.scan_event_label': 'Événement : {event}',
    'organizer.scan_place_label': 'Place : {place}',
    'organizer.scan_client_label': 'Client : {client}',
    'organizer.step_location_seats': 'Lieu & Places',
    'organizer.step_pricing': 'Prix',
    'organizer.edit_event_title': 'Modifier l\'événement',
    'organizer.create_event_title': 'Créer un événement — Étape {step}/5 : {name}',
    'organizer.cancel_edit_title': 'Annuler la modification ?',
    'organizer.cancel_create_title': 'Annuler la création ?',
    'organizer.unsaved_warning': 'Les modifications non enregistrées seront perdues.',
    'organizer.continue_button': 'Continuer',
    'organizer.cancel_button2': 'Annuler',
    'organizer.back_button': 'Retour',
    'organizer.next_button': 'Suivant',
    'organizer.event_updated_msg': 'Événement modifié',
    'organizer.event_created_msg': 'Événement créé',
    'organizer.publish_button': 'Publier l\'événement',
    'organizer.edit_button': 'Modifier l\'événement',
    'organizer.general_info': 'Informations générales',
    'organizer.title_required': 'Titre *',
    'organizer.required_marker': 'Requis',
    'organizer.add_poster': 'Ajouter une affiche',
    'organizer.genre_required': 'Genre *',
    'organizer.placement_type': 'Type de placement',
    'organizer.placement_free': 'Placement\nLibre',
    'organizer.placement_numbered': 'Placement\nNuméroté',
    'organizer.placement_mixed': 'Placement\nMixte',
    'organizer.features_category': 'Caractéristiques {category}',
    'organizer.select_date_placeholder': 'Sélectionner une date',
    'organizer.date_time_title': 'Date & Heure',
    'organizer.date_required': 'Date *',
    'organizer.select_date_hint': 'Sélectionner la date',
    'organizer.num_days_required': 'Nombre de jours *',
    'organizer.day_unit': 'jour',
    'organizer.days_unit': 'jours',
    'organizer.start_time_required': 'Heure début *',
    'organizer.select_time_hint': 'Sélectionner l\'heure',
    'organizer.duration_hours': 'Durée (heures)',
    'organizer.duration_minutes': 'Durée (minutes)',
    'organizer.total_duration_label': 'Durée totale : {duration}',
    'organizer.date_range_label': 'Du {start} au {end} ({days} jour(s))',
    'organizer.location_config': 'Lieu & Configuration',
    'organizer.venue_dropdown': 'Lieu / Bâtiment',
    'organizer.without_room': 'Sans salle spécifique',
    'organizer.no_rooms_available': 'Aucune salle disponible',
    'organizer.capacity_label': 'Capacité',
    'organizer.unlimited_capacity': 'Sans limite de personnes',
    'organizer.max_people_label': 'Nombre max de personnes',
    'organizer.unlimited_hint': 'Laissez vide pour illimité',
    'organizer.seat_types_pricing_label': 'Types de places tarifs',
    'organizer.price_prefix': 'Ar ',
    'organizer.add_standing_zone_title': 'Ajouter une zone debout',
    'organizer.zone_name_label': 'Nom de la zone',
    'organizer.zone_name_hint': 'Fosse, Balcon...',
    'organizer.zone_capacity_label': 'Capacité max',
    'organizer.unlimited_toggle': 'Illimité',
    'organizer.limited_toggle': 'Limitée',
    'organizer.zone_price_label': 'Prix unitaire (Ar)',
    'organizer.add_zone_button': 'Ajouter la zone',
    'organizer.capacity_places': '{capacity} pl.',
    'organizer.seat_types_label': 'Types de places',
    'organizer.seat_types_desc': 'Créez les catégories de places (Standard, VIP, Fosse, Balcon...)',
    'organizer.new_type_hint': 'Nouveau type...',
    'organizer.room_required_label': 'Salle *',
    'organizer.standing_zones_label': 'Zones debout',
    'organizer.zone_capacity_info': '{capacity} pers. max',
    'organizer.zone_capacity_unlimited': 'Sans limite',
    'organizer.zone_price_prefix': 'Ar {price}',
    'organizer.pricing_desc': 'Définissez le prix pour chaque type de place.',
    'organizer.select_room_first_hint': 'Veuillez d\'abord sélectionner une salle à l\'étape précédente.',
    'organizer.seat_plan_config': 'Configurer le plan de salle',
    'organizer.individual_seats': 'Places individuelles',
    'organizer.seats_selected_count': '{count} sélectionnée(s)',
    'organizer.assign_tariff': 'Affecter un type de tarif',
    'organizer.pending_assignments': 'Assignations ({count})',
    'organizer.clear_all': 'Tout effacer',
    'organizer.row_assignment_text': 'Rangée {row} → {type}',
    'organizer.seat_assignment_text': 'Place {seat} → {type}',
    'organizer.places_count_suffix': '{count} place(s)',
    'organizer.tariff_type_title': 'Type de tarif',
    'organizer.no_types_with_price': 'Aucun type de place avec prix défini.',
    'organizer.apply_tariff': 'Appliquer',
    'organizer.summary_title': 'Récapitulatif',
    'organizer.date_time_section': 'Date & Heure',
    'organizer.until_date': 'Jusqu\'au {date} ({days} jours)',
    'organizer.time_display': '{time}',
    'organizer.duration_display': 'Durée : {duration}',
    'organizer.location_section': 'Lieu',
    'organizer.capacity_display': 'Capacité : {capacity} personnes',
    'organizer.placement_pricing_section': 'Placement & Tarifs',
    'organizer.placement_free_display': 'Placement libre',
    'organizer.placement_mixed_display': 'Mixte',
    'organizer.placement_numbered_display': 'Numéroté',
    'organizer.types_display': '{types}',
    'organizer.standing_zones_count': '{count} zone(s) debout',
    'organizer.price_display': '{type} : Ar {price}',
    'organizer.features_section': 'Caractéristiques',
    'organizer.feature_display': '{name} : {value}',
    'organizer.row_prefix': 'Row',
    'organizer.no_row_label': 'No rows',
    'organizer.reservation_count_plain': '{count} reservation(s)',

    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.events': 'Events',
    'admin.categories': 'Categories',
    'admin.venues': 'Venues',
    'admin.places': 'Seats',
    'admin.tickets': 'Tickets',
    'admin.reservations': 'Reservations',
    'admin.payments': 'Payments',
    'admin.account': 'Account',
    'admin.layout.title': 'Admin Panel',

    'settings.title': 'Settings',
    'settings.preferences': 'Preferences',
    'settings.language': 'Language',
    'settings.language.fr': 'Français',
    'settings.language.en': 'English',
    'settings.appearance': 'Appearance',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'settings.theme.system': 'System',
    'settings.security': 'Security',
    'settings.account': 'Account',
    'settings.password2fa': 'Password & 2FA',
    'settings.secured': 'Secured',
    'settings.connectedDevices': 'Connected devices',
    'settings.currentDevice': 'Current device',
    'settings.active': 'Active',
    'settings.othersDisconnected': 'All other devices have been disconnected',
    'settings.disconnectOthers': 'Disconnect other devices',
    'settings.logoutConfirm': 'Do you want to log out?',
    'settings.deleteAccount': 'Delete account',
    'settings.irreversible': 'This action is irreversible',
    'settings.deleteConfirm': 'Do you really want to delete your account? This action is irreversible.',
    'settings.notImplemented': 'Feature not yet implemented',
    'settings.confirm': 'Confirm',
    'settings.about': 'About',
    'settings.appVersion': 'App version',

    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.logout': 'Logout',
    'common.all': 'All',
    'common.retry': 'Retry',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.continue': 'Continue',
    'common.next': 'Next',
    'common.unknown': 'Unknown',

    'admin.dashboard.recentEvents': 'Recent Events',
    'admin.dashboard.analytics': 'Analytics',
    'admin.dashboard.byStatus': 'By status',
    'admin.dashboard.byCategory': 'By category',
    'admin.dashboard.statEvents': 'Events',
    'admin.dashboard.statClients': 'Clients',
    'admin.dashboard.statOrganizers': 'Organizers',
    'admin.dashboard.statRevenue': 'Revenue',
    'admin.dashboard.statVenues': 'Venues',
    'admin.dashboard.statRooms': 'Rooms',

    'admin.events.info': 'Information',
    'admin.events.logistics': 'Logistics',
    'admin.events.capacity': 'Capacity',
    'admin.events.venue': 'Venue',
    'admin.events.date': 'Date',
    'admin.events.time': 'Time',
    'admin.events.noSeatsConfigured': 'No seats configured',
    'admin.events.features': 'Features',
    'admin.events.actions': 'Actions',
    'admin.events.validate': 'Validate / Approve',
    'admin.events.validated': 'Event validated',
    'admin.events.reactivate': 'Reactivate',
    'admin.events.reactivated': 'Event reactivated',
    'admin.events.suspend': 'Suspend',
    'admin.events.suspended': 'Event suspended',
    'admin.events.cancelEvent': 'Cancel Event',
    'admin.events.cancelled': 'Event cancelled',
    'admin.events.contactOrganizer': 'Contact Organizer',
    'admin.events.cancelReason': 'Cancellation reason *',
    'admin.events.cancelReasonHint': 'Mandatory reason',
    'admin.events.contactOptions': 'Contact options:',
    'admin.events.sendEmail': 'Send an email',
    'admin.events.emailNotImplemented': 'Email feature not implemented',
    'admin.events.internalChat': 'Internal chat',
    'admin.events.openChat': 'Open chat',
    'admin.events.chatNotImplemented': 'Chat feature not implemented',
    'admin.events.empty': 'No events found',

    'admin.users.changeRole': 'Change role',
    'admin.users.roleOrganizer': 'Organizer',
    'admin.users.roleClient': 'Client',
    'admin.users.resetPassword': 'Reset password',
    'admin.users.newPassword': 'New password',
    'admin.users.newPasswordHint': 'Enter a new password',
    'admin.users.passwordReset': 'Password reset',
    'admin.users.deleteUser': 'Delete user',
    'admin.users.management': 'User management',
    'admin.users.audit': 'Audit',
    'admin.users.empty': 'No users found',
    'admin.users.active': 'Active',
    'admin.users.inactive': 'Inactive',
    'admin.users.new': 'New',
    'admin.users.role': 'Role',
    'admin.users.deactivate': 'Deactivate',
    'admin.users.activate': 'Activate',
    'admin.users.resetPwd': 'Reset PWD',
    'admin.users.noActivity': 'No activity',

    'admin.categories.add': 'Add category',
    'admin.categories.code': 'Code',
    'admin.categories.codeHint': 'CAT01',
    'admin.categories.name': 'Name',
    'admin.categories.description': 'Description',
    'admin.categories.edit': 'Edit category',
    'admin.categories.deleteTitle': 'Delete category',
    'admin.categories.deleted': 'Category deleted',
    'admin.categories.empty': 'No categories found',
    'admin.categories.features': 'Features',
    'admin.categories.rooms': 'Rooms',
    'admin.categories.config': 'Config',
    'admin.categories.addFeature': 'Add a feature',
    'admin.categories.editFeature': 'Edit feature',
    'admin.categories.dataType': 'Data type',
    'admin.categories.dataTypeText': 'Text',
    'admin.categories.dataTypeNumber': 'Number',
    'admin.categories.dataTypeDate': 'Date',
    'admin.categories.dataTypeSelect': 'Dropdown list',
    'admin.categories.dataTypeBoolean': 'Yes/No',
    'admin.categories.displayOrder': 'Display order',
    'admin.categories.options': 'Options (comma separated)',
    'admin.categories.required': 'Required',
    'admin.categories.noFeatures': 'No features',
    'admin.categories.compatibleRoomTypes': 'Compatible room types',
    'admin.categories.configSaved': 'Specific configuration saved',
    'admin.categories.cinemaConfig': 'Cinema room configuration',
    'admin.categories.numRows': 'Number of rows',
    'admin.categories.seatsPerRow': 'Seats per row',
    'admin.categories.aisles': 'Aisles (ex: B,D)',
    'admin.categories.aisleWidth': 'Aisle width',
    'admin.categories.freeSeatingZones': 'Free seating zones',
    'admin.categories.noZones': 'No zones configured',
    'admin.categories.addZone': 'Add a zone',
    'admin.categories.maxCapacity': 'Max capacity',
    'admin.categories.ticketPrice': 'Ticket price',
    'admin.categories.standsBlocks': 'Stand blocks',
    'admin.categories.noBlocks': 'No blocks configured',
    'admin.categories.addBlock': 'Add a block',
    'admin.categories.blockType': 'Type (ex: Stand A)',
    'admin.categories.numSeats': 'Number of seats',
    'admin.categories.price': 'Price',
    'admin.categories.type': 'Type',
    'admin.categories.noSpecificConfig': 'No specific configuration available for this category',

    'admin.venues.roomsFor': 'Rooms —',
    'admin.venues.noRooms': 'No rooms for this venue',
    'admin.venues.addRoom': 'Add a room',
    'admin.venues.manageSeats': 'Manage seats',
    'admin.venues.roomName': 'Room name',
    'admin.venues.venueCode': 'Venue code',
    'admin.venues.name': 'Name',
    'admin.venues.address': 'Address',
    'admin.venues.city': 'City',
    'admin.venues.empty': 'No venues found',
    'admin.venues.selectRoomType': 'Select rooms compatible with',

    'admin.places.roomDeleted': 'Room deleted',
    'admin.places.seatDeleted': 'Seat deleted',
    'admin.places.editSeat': 'Edit seat',
    'admin.places.seatNumber': 'Seat number',
    'admin.places.row': 'Row',
    'admin.places.editRoom': 'Edit room',
    'admin.places.addRoom': 'Add a room',
    'admin.places.parentVenue': 'Parent venue',
    'admin.places.roomsAndSeats': 'Rooms & Seats',
    'admin.places.searchRoom': 'Search a room...',
    'admin.places.filterByVenue': 'Filter by venue',
    'admin.places.allVenues': 'All venues',
    'admin.places.noRooms': 'No rooms found',
    'admin.places.manageSeats': 'Manage seats',
    'admin.places.multiSelect': 'Multi select',
    'admin.places.batchGeneration': 'Batch generation',
    'admin.places.rowHint': 'B',
    'admin.places.startNum': 'Start #',
    'admin.places.endNum': 'End #',
    'admin.places.generate': 'Generate',
    'admin.places.searchSeat': 'Search a seat...',
    'admin.places.noSeats': 'No seats for this room',
    'admin.places.noSeatsMatch': 'No seats match your search',
    'admin.places.deselect': 'Deselect',
    'admin.places.select': 'Select',
    'admin.places.bulkDelete': 'Bulk delete',

    'admin.tickets.empty': 'No tickets found',

    'admin.reservations.empty': 'No reservations found',

    'admin.payments.empty': 'No payments found',

    'admin.profile.personalInfo': 'Personal information',
    'admin.profile.lastName': 'Last name',
    'admin.profile.firstName': 'First name',
    'admin.profile.saveConfirm': 'Do you want to save the changes?',
    'admin.profile.updated': 'Information updated',
    'admin.profile.actionHistory': 'Action history',
    'admin.profile.logoutConfirm': 'Do you really want to log out?',

    'admin.actionHistory.undoAction': 'Undo action',
    'admin.actionHistory.yesUndo': 'Yes, undo',
    'admin.actionHistory.actionUndone': 'Action undone',
    'admin.actionHistory.createUser': 'User creation',
    'admin.actionHistory.updateUser': 'User update',
    'admin.actionHistory.changeRole': 'Role change',
    'admin.actionHistory.deactivateUser': 'User deactivation',
    'admin.actionHistory.activateUser': 'User activation',
    'admin.actionHistory.resetPassword': 'Password reset',
    'admin.actionHistory.deleteUser': 'User deletion',
    'admin.actionHistory.paymentMade': 'Payment made',
    'admin.actionHistory.refund': 'Refund',
    'admin.actionHistory.title': 'Action history',
    'admin.actionHistory.empty': 'No actions recorded',
    'admin.actionHistory.reverted': 'Reverted',
    'admin.actionHistory.undo': 'Undo',

    'notifications.title': 'Notifications',
    'notifications.empty': 'No notifications',
    'notifications.notConnected': 'User not connected',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.markAllReadShort': 'Read all',
    'notifications.filterAll': 'All',
    'notifications.filterPayments': 'Payments',
    'notifications.filterFailed': 'Failed',
    'notifications.filterReservations': 'Reservations',
    'notifications.filterCancellations': 'Cancellations',
    'notifications.filterCancelled': 'Cancelled',
    'notifications.filterApproved': 'Approved',
    'notifications.filterUpdated': 'Updated',
    'notifications.filterSuspended': 'Suspended',
    'notifications.filterScanned': 'Scanned',
    'notifications.filterReused': 'Reused',
    'notifications.filterRefunded': 'Refunded',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.read': 'Read',
    'notifications.noResults': 'No results',
    'notifications.emptyFiltered': 'No notifications match the selected filters.\nModify or reset filters to see more results.',
    'notifications.emptyGeneral': 'You will be notified here about important updates.\nBook tickets or create events to receive notifications.',
    'notifications.resetFilters': 'Reset filters',

    'pageNotFound.title': 'Page not found',
    'pageNotFound.home': 'Home',

    'widgets.error.retry': 'Retry',
    'widgets.seat_picker.row': 'Row',

    'widgets.crud.confirm': 'Confirm',
    'widgets.crud.delete_confirm': 'Delete this item?',
    'widgets.crud.cancel': 'Cancel',
    'widgets.crud.delete': 'Delete',
    'widgets.crud.bulk_delete_title': 'Bulk delete',
    'widgets.crud.bulk_delete_confirm': 'Delete {n} item(s)?',
    'widgets.crud.delete_all': 'Delete all',
    'widgets.crud.edit': 'Edit',
    'widgets.crud.add': 'Add',
    'widgets.crud.save': 'Save',
    'widgets.crud.required': 'Required',
    'widgets.crud.select_date': 'Select a date',
    'widgets.crud.select_all': 'Select all',
    'widgets.crud.delete_selection': 'Delete selection',
    'widgets.crud.exit_select_mode': 'Exit select mode',
    'widgets.crud.select_mode': 'Select mode',
    'widgets.crud.search': 'Search...',
    'widgets.crud.all': 'All',
    'widgets.crud.retry': 'Retry',
    'widgets.crud.empty': 'No items',

    'widgets.code_promo.label': 'Promo code',
    'widgets.code_promo.hint': 'Enter your promo code',
    'widgets.code_promo.apply': 'Apply',
    'widgets.code_promo.applied': 'Promo code applied!',

    'widgets.carte_bancaire.title': 'Bank card information',
    'widgets.carte_bancaire.card_number': 'Card number',
    'widgets.carte_bancaire.card_number_hint': '1234 5678 9012 3456',
    'widgets.carte_bancaire.expiry': 'Expiry date',
    'widgets.carte_bancaire.expiry_hint': 'MM/YY',
    'widgets.carte_bancaire.cvv': 'CVV',
    'widgets.carte_bancaire.cvv_hint': '123',
    'widgets.carte_bancaire.cardholder_name': 'Cardholder name',
    'widgets.carte_bancaire.cardholder_name_hint': 'JOHN DOE',

    'widgets.payment_method.title': 'Payment method',

    'widgets.two_factor.disable_2fa': 'Disable 2FA',
    'widgets.two_factor.disable_2fa_confirm': 'Are you sure you want to disable two-factor authentication?',
    'widgets.two_factor.cancel': 'Cancel',
    'widgets.two_factor.disable': 'Disable',
    'widgets.two_factor.password_2fa': 'Password & 2FA',
    'widgets.two_factor.2fa_label': 'Two-factor authentication',
    'widgets.two_factor.2fa_enabled_desc': '6-digit code sent by email',
    'widgets.two_factor.2fa_disabled_desc': 'Enable to secure your account',
    'widgets.two_factor.change_password_title': 'Change password',
    'widgets.two_factor.current_password': 'Current password',
    'widgets.two_factor.new_password': 'New password',
    'widgets.two_factor.confirm_password': 'Confirm',
    'widgets.two_factor.password_length_error': 'Password must be at least 6 characters',
    'widgets.two_factor.password_mismatch_error': 'Passwords do not match',
    'widgets.two_factor.password_changed': 'Password changed',
    'widgets.two_factor.change_password': 'Change password',
    'widgets.two_factor.activate_2fa': 'Enable 2FA',
    'widgets.two_factor.2fa_email_desc': 'A 6-digit code will be sent to your email address.',
    'widgets.two_factor.sending': 'Sending...',
    'widgets.two_factor.send_code': 'Send code',
    'widgets.two_factor.code_hint': '000000',
    'widgets.two_factor.2fa_activated': '2FA enabled',
    'widgets.two_factor.incorrect_code': 'Incorrect code',
    'widgets.two_factor.verify_activate': 'Verify & activate',

    'widgets.notification_bell.tooltip': 'Notifications',

    'widgets.profile.logout': 'Logout',
  };

  static Map<String, String> _en = {
    'app.title': 'Ontik',
    'app.loading': 'Loading...',

    'splash.title': 'Ontik',

    'auth.login.title': 'Login',
    'auth.login.email': 'Email',
    'auth.login.password': 'Password',
    'auth.login.submit': 'Sign in',
    'auth.login.forgotPassword': 'Forgot password?',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.register': "Register",
    'auth.login.welcome': 'Welcome back',

    'auth.register.title': 'Register',
    'auth.register.submit': "Sign up",
    'auth.register.haveAccount': 'Already have an account?',
    'auth.register.login': 'Sign in',

    'auth.forgotPassword.title': 'Forgot password',
    'auth.register.success': 'Registration successful. Please log in.',

    'client.home': 'Events',
    'client.tickets': 'My Tickets',
    'client.account': 'Account',
    'client.profile.title': 'My Profile',
    'client.layout.title': 'Ontik',
    'client.home.filters': 'Filters',
    'client.home.reset': 'Reset',
    'client.home.status': 'Status',
    'client.home.venue': 'Venue',
    'client.home.allVenues': 'All venues',
    'client.home.selectDateRange': 'Select a range',
    'client.home.apply': 'Apply',
    'client.home.searchHint': 'Search events...',
    'client.home.featured': 'Featured events',
    'client.home.noEvents': 'No events found',
    'client.home.venueNotSpecified': 'Venue not specified',
    'client.home.priceUnavailable': 'Price unavailable',
    'client.home.standard': 'Standard',
    'client.home.promoTitle': '-20% on your first ticket',
    'client.home.promoSubtitle': 'Use code SECURE20 at checkout.',
    'client.home.retry': 'Retry',
    'client.homeDetail.share': 'Share',
    'client.homeDetail.retry': 'Retry',
    'client.homeDetail.eventNotFound': 'Event not found',
    'client.homeDetail.event': 'EVENT',
    'client.homeDetail.date': 'Date',
    'client.homeDetail.time': 'Time',
    'client.homeDetail.venueNotSpecified': 'Venue not specified',
    'client.homeDetail.about': 'About the event',
    'client.homeDetail.noDescription': 'No description available.',
    'client.homeDetail.characteristic': 'Characteristic',
    'client.homeDetail.availableZones': 'Available zones',
    'client.homeDetail.unlimitedSeats': 'Unlimited seats',
    'client.homeDetail.placesAvailable': 'seats available',
    'client.homeDetail.priceUnavailable': 'Price unavailable',
    'client.homeDetail.from': 'From',
    'client.homeDetail.book': 'BOOK MY SEAT',
    'client.profile.myReservations': 'My Reservations',
    'client.profile.reservationsTab': 'Reservations',
    'client.profile.ticketsTab': 'Tickets',
    'client.profile.referenceCodes': 'Reference codes',
    'client.profile.noReservations': 'No reservations',
    'client.profile.reservationsWillAppear': 'Your reservations will appear here.',
    'client.profile.unknownDate': 'Unknown date',
    'client.profile.reservationReference': 'Reservation reference',
    'client.profile.noTickets': 'No tickets',
    'client.profile.ticketsWillAppear': 'Your tickets will appear here after booking.',
    'client.profile.event': 'Event',
    'client.profile.room': 'Room',
    'client.profile.row': 'Row',
    'client.profile.seat': 'Seat',
    'client.profile.reference': 'Reference',
    'client.profile.expired': 'EXPIRED',
    'client.profile.reservation': 'Reservation',
    'client.profile.ticketsCount': 'ticket(s)',
    'client.profile.personalInfo': 'Personal information',
    'client.profile.lastName': 'Last name',
    'client.profile.firstName': 'First name',
    'client.profile.phone': 'Phone',
    'client.profile.confirm': 'Confirm',
    'client.profile.confirmSave': 'Do you want to save the changes?',
    'client.profile.updated': 'Information updated',
    'client.profile.paymentMethods': 'Payment methods',
    'client.profile.paymentHistoryComing': 'Payment history — coming soon.',
    'client.profile.close': 'Close',
    'client.profile.confirmLogout': 'Do you really want to log out?',
    'client.profile.user': 'User',
    'client.profile.favorites': 'Favorites',
    'client.profile.alerts': 'Alerts',
    'client.profile.accountGroup': 'Account',
    'client.profile.securityGroup': 'Security',
    'client.profile.password2FA': 'Password & 2FA',
    'client.profile.secure': 'Secured',
    'client.profile.connectedDevices': 'Connected devices',
    'client.reservation.share': 'Share',
    'client.reservation.eventNotFound': 'Event not found',
    'client.reservation.noSeatsAvailable': 'No seats available',
    'client.reservation.stage': 'STAGE',
    'client.reservation.selectBlock': 'Select a block to see available seats',
    'client.reservation.noSeatsInBlock': 'No seats available in this block',
    'client.reservation.blockView': 'View from block',
    'client.reservation.noStandingZones': 'No standing zones available',
    'client.reservation.standingZones': 'Standing zones',
    'client.reservation.unlimitedSeats': 'Unlimited seats',
    'client.reservation.selectedSeats': 'SELECTED SEATS',
    'client.reservation.confirmSelection': 'Confirm selection',
    'client.reservation.selectInBlock': 'Select your seats in the block',
    'client.reservation.places': 'seats',
    'client.reservation.remainingSeats': 'seat(s) remaining out of',
    'client.reservation.tickets': 'ticket(s)',
    'client.reservation.estimatedTotal': 'ESTIMATED TOTAL',
    'client.payment.processing': 'Processing payment...',
    'client.payment.paymentMethod': 'Payment method',
    'client.payment.summary': 'Summary',
    'client.payment.venue': 'VENUE',
    'client.payment.event': 'Event',
    'client.payment.price': 'PRICE',
    'client.payment.row': 'ROW',
    'client.payment.seat': 'SEAT',
    'client.payment.tickets': 'TICKETS',
    'client.payment.orderVerified': 'Order verified',
    'client.payment.card': 'Bank Card',
    'client.payment.cardSubtitle': 'Visa, Mastercard, AMEX',
    'client.payment.mvolaSubtitle': 'MVola mobile payment',
    'client.payment.orangeSubtitle': 'Orange mobile payment',
    'client.payment.airtelSubtitle': 'Airtel mobile payment',
    'client.payment.transactionRef': 'Transaction reference',
    'client.payment.phoneNumber': 'Phone number',
    'client.payment.fullName': 'Full name',
    'client.payment.securityDisclaimer': 'Your payment data is end-to-end encrypted. We are PCI-DSS Level 1 certified.',
    'client.payment.errorTransactionRef': 'Transaction reference is required',
    'client.payment.errorPhoneNumber': 'Phone number is required',
    'client.payment.errorCardInfo': 'Card information is required',
    'client.payment.errorNotLoggedIn': 'User not logged in',
    'client.payment.success': 'Booking successful!',
    'client.payment.errorTimeout': 'Server not responding. Check your connection.',
    'client.payment.errorSeatTaken': 'Seat already booked or unavailable. Please try again.',
    'client.payment.errorInsufficientFunds': 'Insufficient funds for this transaction.',
    'client.payment.errorPromoCode': 'Invalid or expired promo code.',
    'client.payment.successReduction': 'Booking successful! Reduction of',
    'client.payment.pay': 'Pay',
    'client.ticket.title': 'Ticket',
    'client.ticket.notFound': 'Ticket not found',
    'client.ticket.valid': 'VALID',
    'client.ticket.invalid': 'INVALID',
    'client.ticket.downloadPDF': 'Download PDF',
    'client.ticket.event': 'Event',
    'client.ticket.seat': 'Seat',
    'client.ticket.row': 'Row',
    'client.ticket.type': 'Type',
    'client.ticket.zone': 'Zone',
    'client.ticket.price': 'Price',
    'client.ticket.holder': 'Holder',
    'client.ticket.noTickets': 'No tickets',
    'client.ticket.afterPurchase': 'Your tickets will appear here after purchase.',
    'client.ticket.myTickets': 'My Tickets',
    'client.ticket.manageTickets': 'Manage your access and reservations',
    'client.ticket.room': 'Room',
    'client.ticket.pdfSaved': 'PDF saved to',
    'client.ticket.downloadFailed': 'Download failed:',
    'client.ticket.reference': 'Reference',
    'client.ticket.expired': 'EXPIRED',

    'organizer.dashboard': 'Dashboard',
    'organizer.events': 'Events',
    'organizer.tickets': 'Tickets',
    'organizer.reservations': 'Reservations',
    'organizer.account': 'Account',
    'organizer.layout.title': 'Ontik — Organizer',
    'organizer.profile.title': 'Profile',
    'organizer.overview': 'Overview',
    'organizer.events_active': '{count} active events',
    'organizer.manage': 'Manage',
    'organizer.revenue': 'Revenue',
    'organizer.fill_rate': 'Fill rate',
    'organizer.tickets_sold': 'Tickets sold',
    'organizer.seats_available': 'Seats avail.',
    'organizer.my_events': 'My events',
    'organizer.see_all': 'See all',
    'organizer.sales_evolution': 'Sales evolution',
    'organizer.top_events': 'Top events',
    'organizer.suspend_event_title': 'Suspend event',
    'organizer.suspend_confirm': 'Suspend "{event}"? Existing reservations will be kept.',
    'organizer.suspend': 'Suspend',
    'organizer.event_suspended': 'Event suspended',
    'organizer.event_resumed': 'Event reactivated',
    'organizer.cancel_event_title': 'Cancel event',
    'organizer.cancel_confirm': 'Are you sure you want to cancel "{event}"?',
    'organizer.cancel_notify': 'Booked customers will be notified.',
    'organizer.cancel_reason': 'Cancellation reason',
    'organizer.cancel_event': 'Cancel event',
    'organizer.event_cancelled': 'Event cancelled',
    'organizer.info': 'Info',
    'organizer.reactivate': 'Reactivate',
    'organizer.no_events': 'No events',
    'organizer.create_event': 'Create Event',
    'organizer.status_label': 'Status',
    'organizer.date_label': 'Date',
    'organizer.time_label': 'Time',
    'organizer.countdown_label': 'Countdown',
    'organizer.description_label': 'Description',
    'organizer.category_label': 'Category',
    'organizer.location_label': 'Venue',
    'organizer.organizer_label': 'Organizer',
    'organizer.features_label': 'Features',
    'organizer.feature': 'Feature',
    'organizer.ended_min': 'Ended {count} min ago',
    'organizer.ended_h': 'Ended {count}h ago',
    'organizer.ended_d': 'Ended {count}d ago',
    'organizer.ended_months': 'Ended {count} months ago',
    'organizer.ended_years': 'Ended {count} year(s) ago',
    'organizer.starts_min': 'Starts in {count} min',
    'organizer.starts_h': 'Starts in {count}h',
    'organizer.starts_d': 'Starts in {count}d',
    'organizer.personal_info': 'Personal information',
    'organizer.last_name': 'Last name',
    'organizer.first_name': 'First name',
    'organizer.phone': 'Phone',
    'organizer.save_changes_confirm': 'Do you want to save the changes?',
    'organizer.profile_updated': 'Profile updated',
    'organizer.total_revenue': 'Total revenue',
    'organizer.load_error': 'Load error',
    'organizer.latest_sales': 'Latest sales',
    'organizer.logout_confirm': 'Do you really want to log out?',
    'organizer.org_code_missing': 'Organizer code not found. Please reconnect.',
    'organizer.today': 'Today',
    'organizer.last_7_days': '7 days',
    'organizer.last_30_days': '30 days',
    'organizer.search_client': 'Search client...',
    'organizer.paid': 'Paid',
    'organizer.pending': 'Pending',
    'organizer.cancelled': 'Cancelled',
    'organizer.reservation_count': '{count} reservation(s)',
    'organizer.no_reservations_for_event': 'No reservations for this event',
    'organizer.select_event': 'Select an event',
    'organizer.no_reservations': 'No reservations',
    'organizer.ticket_count': '{count} ticket(s)',
    'organizer.full_detail': 'Full detail',
    'organizer.view_event': 'View event',
    'organizer.available': 'Available',
    'organizer.scanned': 'Scanned',
    'organizer.pending_short': 'Pending',
    'organizer.pricing_title': 'Pricing — {title}',
    'organizer.room_label': 'Room:',
    'organizer.price_by_type': 'Price by seat type',
    'organizer.price_by_type_desc': 'Set the price for each seat type. All seats of this type will be updated.',
    'organizer.price': 'Price',
    'organizer.apply': 'Apply',
    'organizer.type_assignment': 'Type assignment',
    'organizer.type_assignment_desc': 'Select rows or seats and assign them a type.',
    'organizer.type_to_assign': 'Type to assign',
    'organizer.new_type': '+ New type...',
    'organizer.assign': 'Assign',
    'organizer.selection_count': '{rows} row(s) • {seats} seat(s) selected',
    'organizer.no_rows': 'No rows available',
    'organizer.click_seat_to_select': 'Click a seat in the grid below to select it',
    'organizer.row_pricing': 'Pricing by row',
    'organizer.row_pricing_desc': 'Configure type and price for each row.',
    'organizer.seat_grid': 'Individual grid',
    'organizer.search_seat': 'Search seat...',
    'organizer.type': 'Type',
    'organizer.seat_count_label': '{total} seats • {configured} configured',
    'organizer.configured': 'configured',
    'organizer.price_with_currency': 'Price ({currency})',
    'organizer.new_type_name': 'New type',
    'organizer.confirm_refund': 'Confirm refund',
    'organizer.refunds_title': 'Refunds and cancellations',
    'organizer.cancelled_badge': 'CANCELLED',
    'organizer.refund_action': 'Refund',
    'organizer.data_export': 'Data export',
    'organizer.select_event_export': 'Select an event to export data',
    'organizer.tickets_csv': 'Tickets CSV',
    'organizer.reservations_csv': 'Reserv. CSV',
    'organizer.scan_ticket': 'Scan a ticket',
    'organizer.scan_next': 'Scan next',
    'organizer.align_qr': 'Align the QR code within the frame',
    'organizer.ticket_valid': 'Valid ticket',
    'organizer.ticket_invalid': 'Invalid ticket',
    'organizer.step_infos': 'Info',
    'organizer.step_date_time': 'Date & Time',
    'organizer.step_location': 'Venue & Seats',
    'organizer.step_summary': 'Summary',
    'organizer.edit_event': 'Edit event',
    'organizer.cancel_edit': 'Cancel changes?',
    'organizer.cancel_create': 'Cancel creation?',
    'organizer.unsaved_changes': 'Unsaved changes will be lost.',
    'organizer.event_updated': 'Event updated',
    'organizer.event_created': 'Event created',
    'organizer.publish_event': 'Publish event',

    'organizer.status_suspended': 'Suspended',
    'organizer.status_cancelled': 'Cancelled',
    'organizer.status_upcoming': 'Upcoming',
    'organizer.status_in_progress': 'In progress',
    'organizer.status_ended': 'Ended',
    'organizer.event_label': 'Event',
    'organizer.period_today': 'Today',
    'organizer.period_7days': '7 days',
    'organizer.period_30days': '30 days',
    'organizer.search_client_hint': 'Search client...',
    'organizer.status_paid': 'Paid',
    'organizer.status_pending': 'Pending',
    'organizer.status_cancelled_short': 'Cancelled',
    'organizer.retry_button': 'Retry',
    'organizer.unknown_client': 'Unknown',
    'organizer.tickets_count': '{count} ticket(s)',
    'organizer.seat_place': 'Seat {seat}',
    'organizer.full_detail_button': 'Full detail',
    'organizer.view_event_button': 'View event',
    'organizer.reservation_header': 'Reservation #{id}',
    'organizer.client_section': 'Client',
    'organizer.name_field': 'Name',
    'organizer.code_field': 'Code',
    'organizer.email_field': 'Email',
    'organizer.phone_field': 'Phone',
    'organizer.payment_section': 'Payment',
    'organizer.amount_field': 'Amount',
    'organizer.mode_field': 'Method',
    'organizer.payment_date_field': 'Date',
    'organizer.status_field': 'Status',
    'organizer.tickets_section': 'Tickets',
    'organizer.no_tickets_text': 'No tickets',
    'organizer.seat_place_detail': 'Seat {seat}',
    'organizer.row_detail': 'Row {row}',
    'organizer.org_code_missing_reconnect': 'Organizer code not found. Please reconnect.',
    'organizer.paid_status': 'Paid',
    'organizer.pending_status': 'Pending',
    'organizer.available_status': 'Available',
    'organizer.scanned_status': 'Scanned',
    'organizer.unknown_status': 'Unknown',
    'organizer.event_dropdown': 'Event',
    'organizer.all_filter': 'All',
    'organizer.paid_filter': 'Paid',
    'organizer.pending_filter': 'Pending',
    'organizer.pricing_applied_row': 'Pricing applied to row {row}',
    'organizer.pricing_applied_type': 'Price applied to type {type}',
    'organizer.select_min_row_or_seat': 'Select at least one row or seat',
    'organizer.type_assigned_msg': 'Type {type} assigned',
    'organizer.seat_updated_msg': 'Seat {seat} updated',
    'organizer.pricing_header': 'Pricing — {title}',
    'organizer.room_selector': 'Room:',
    'organizer.price_by_type_title': 'Price by seat type',
    'organizer.price_field': 'Price',
    'organizer.apply_button': 'Apply',
    'organizer.type_assignment_title': 'Type assignment',
    'organizer.new_type_option': '+ New type...',
    'organizer.name_placeholder': 'Name',
    'organizer.assign_button': 'Assign',
    'organizer.no_rows_available': 'No rows available',
    'organizer.row_pricing_title': 'Pricing by row',
    'organizer.seat_grid_title': 'Individual grid',
    'organizer.search_seat_hint': 'Search seat...',
    'organizer.type_dropdown': 'Type',
    'organizer.all_option': 'All',
    'organizer.seat_count_configured': '{total} seats • {configured} configured',
    'organizer.seat_dialog_title': 'Seat {seat}',
    'organizer.new_type_label': 'New type',
    'organizer.price_currency': 'Price ({currency})',
    'organizer.cancel_button': 'Cancel',
    'organizer.save_button': 'Save',
    'organizer.row_title': 'Row {row}  ({count} seats)',
    'organizer.configured_badge': 'configured',
    'organizer.type_field': 'Type',
    'organizer.confirm_refund_title': 'Confirm refund',
    'organizer.confirm_refund_text': 'Do you want to cancel and refund reservation #{id}?',
    'organizer.cancel_refund_button': 'Cancel',
    'organizer.confirm_refund_button': 'Confirm',
    'organizer.refund_result_message': 'Reservation #{id} cancelled. Refund: {amount} {currency}',
    'organizer.cancelled_badge_label': 'CANCELLED',
    'organizer.refund_action_button': 'Refund',
    'organizer.export_title': 'Data export',
    'organizer.export_subtitle': 'Select an event to export data',
    'organizer.no_events_export': 'No events',
    'organizer.export_tickets_csv': 'Tickets CSV',
    'organizer.export_reservations_csv': 'Reserv. CSV',
    'organizer.export_all_button': 'All',
    'organizer.export_saved_message': 'File saved: {filename}',
    'organizer.export_error_prefix': 'Error: {message}',
    'organizer.scan_title': 'Scan a ticket',
    'organizer.scan_align_qr': 'Align the QR code within the frame',
    'organizer.scan_valid': 'Valid ticket',
    'organizer.scan_invalid': 'Invalid ticket',
    'organizer.scan_code_label': 'Code: {code}',
    'organizer.scan_event_label': 'Event: {event}',
    'organizer.scan_place_label': 'Seat: {place}',
    'organizer.scan_client_label': 'Client: {client}',
    'organizer.step_location_seats': 'Venue & Seats',
    'organizer.step_pricing': 'Pricing',
    'organizer.edit_event_title': 'Edit event',
    'organizer.create_event_title': 'Create event — Step {step}/5: {name}',
    'organizer.cancel_edit_title': 'Cancel changes?',
    'organizer.cancel_create_title': 'Cancel creation?',
    'organizer.unsaved_warning': 'Unsaved changes will be lost.',
    'organizer.continue_button': 'Continue',
    'organizer.cancel_button2': 'Cancel',
    'organizer.back_button': 'Back',
    'organizer.next_button': 'Next',
    'organizer.event_updated_msg': 'Event updated',
    'organizer.event_created_msg': 'Event created',
    'organizer.publish_button': 'Publish event',
    'organizer.edit_button': 'Edit event',
    'organizer.general_info': 'General information',
    'organizer.title_required': 'Title *',
    'organizer.required_marker': 'Required',
    'organizer.add_poster': 'Add poster',
    'organizer.genre_required': 'Genre *',
    'organizer.placement_type': 'Placement type',
    'organizer.placement_free': 'Free\nSeating',
    'organizer.placement_numbered': 'Numbered\nSeating',
    'organizer.placement_mixed': 'Mixed\nSeating',
    'organizer.features_category': 'Features {category}',
    'organizer.select_date_placeholder': 'Select a date',
    'organizer.date_time_title': 'Date & Time',
    'organizer.date_required': 'Date *',
    'organizer.select_date_hint': 'Select date',
    'organizer.num_days_required': 'Number of days *',
    'organizer.day_unit': 'day',
    'organizer.days_unit': 'days',
    'organizer.start_time_required': 'Start time *',
    'organizer.select_time_hint': 'Select time',
    'organizer.duration_hours': 'Duration (hours)',
    'organizer.duration_minutes': 'Duration (minutes)',
    'organizer.total_duration_label': 'Total duration: {duration}',
    'organizer.date_range_label': 'From {start} to {end} ({days} day(s))',
    'organizer.location_config': 'Venue & Configuration',
    'organizer.venue_dropdown': 'Venue / Building',
    'organizer.without_room': 'Without specific room',
    'organizer.no_rooms_available': 'No rooms available',
    'organizer.capacity_label': 'Capacity',
    'organizer.unlimited_capacity': 'Unlimited people',
    'organizer.max_people_label': 'Max people',
    'organizer.unlimited_hint': 'Leave empty for unlimited',
    'organizer.seat_types_pricing_label': 'Seat types & prices',
    'organizer.price_prefix': '',
    'organizer.add_standing_zone_title': 'Add a standing zone',
    'organizer.zone_name_label': 'Zone name',
    'organizer.zone_name_hint': 'Pit, Balcony...',
    'organizer.zone_capacity_label': 'Max capacity',
    'organizer.unlimited_toggle': 'Unlimited',
    'organizer.limited_toggle': 'Limited',
    'organizer.zone_price_label': 'Unit price',
    'organizer.add_zone_button': 'Add zone',
    'organizer.capacity_places': '{capacity} seats',
    'organizer.seat_types_label': 'Seat types',
    'organizer.seat_types_desc': 'Create seat categories (Standard, VIP, Pit, Balcony...)',
    'organizer.new_type_hint': 'New type...',
    'organizer.room_required_label': 'Room *',
    'organizer.standing_zones_label': 'Standing zones',
    'organizer.zone_capacity_info': '{capacity} people max',
    'organizer.zone_capacity_unlimited': 'Unlimited',
    'organizer.zone_price_prefix': '{price}',
    'organizer.pricing_desc': 'Set the price for each seat type.',
    'organizer.select_room_first_hint': 'Please select a room in the previous step first.',
    'organizer.seat_plan_config': 'Configure seating plan',
    'organizer.individual_seats': 'Individual seats',
    'organizer.seats_selected_count': '{count} selected',
    'organizer.assign_tariff': 'Assign a tariff type',
    'organizer.pending_assignments': 'Assignments ({count})',
    'organizer.clear_all': 'Clear all',
    'organizer.row_assignment_text': 'Row {row} → {type}',
    'organizer.seat_assignment_text': 'Seat {seat} → {type}',
    'organizer.places_count_suffix': '{count} seat(s)',
    'organizer.tariff_type_title': 'Tariff type',
    'organizer.no_types_with_price': 'No seat types with a defined price.',
    'organizer.apply_tariff': 'Apply',
    'organizer.summary_title': 'Summary',
    'organizer.date_time_section': 'Date & Time',
    'organizer.until_date': 'Until {date} ({days} days)',
    'organizer.time_display': '{time}',
    'organizer.duration_display': 'Duration: {duration}',
    'organizer.location_section': 'Venue',
    'organizer.capacity_display': 'Capacity: {capacity} people',
    'organizer.placement_pricing_section': 'Placement & Pricing',
    'organizer.placement_free_display': 'Free seating',
    'organizer.placement_mixed_display': 'Mixed',
    'organizer.placement_numbered_display': 'Numbered',
    'organizer.types_display': '{types}',
    'organizer.standing_zones_count': '{count} standing zone(s)',
    'organizer.price_display': '{type}: {price}',
    'organizer.features_section': 'Features',
    'organizer.feature_display': '{name}: {value}',
    'organizer.row_prefix': 'Row',
    'organizer.no_row_label': 'No rows',
    'organizer.reservation_count_plain': '{count} reservation(s)',

    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.events': 'Events',
    'admin.categories': 'Categories',
    'admin.venues': 'Venues',
    'admin.places': 'Seats',
    'admin.tickets': 'Tickets',
    'admin.reservations': 'Reservations',
    'admin.payments': 'Payments',
    'admin.account': 'Account',
    'admin.layout.title': 'Admin Panel',

    'settings.title': 'Settings',
    'settings.preferences': 'Preferences',
    'settings.language': 'Language',
    'settings.language.fr': 'Français',
    'settings.language.en': 'English',
    'settings.appearance': 'Appearance',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'settings.theme.system': 'System',
    'settings.security': 'Security',
    'settings.account': 'Account',
    'settings.password2fa': 'Password & 2FA',
    'settings.secured': 'Secured',
    'settings.connectedDevices': 'Connected devices',
    'settings.currentDevice': 'Current device',
    'settings.active': 'Active',
    'settings.othersDisconnected': 'All other devices have been disconnected',
    'settings.disconnectOthers': 'Disconnect other devices',
    'settings.logoutConfirm': 'Do you want to log out?',
    'settings.deleteAccount': 'Delete account',
    'settings.irreversible': 'This action is irreversible',
    'settings.deleteConfirm': 'Do you really want to delete your account? This action is irreversible.',
    'settings.notImplemented': 'Feature not yet implemented',
    'settings.confirm': 'Confirm',
    'settings.about': 'About',
    'settings.appVersion': 'App version',

    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.logout': 'Logout',
    'common.all': 'All',
    'common.retry': 'Retry',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.continue': 'Continue',
    'common.next': 'Next',
    'common.unknown': 'Unknown',

    'admin.dashboard.recentEvents': 'Recent Events',
    'admin.dashboard.analytics': 'Analytics',
    'admin.dashboard.byStatus': 'By status',
    'admin.dashboard.byCategory': 'By category',
    'admin.dashboard.statEvents': 'Events',
    'admin.dashboard.statClients': 'Clients',
    'admin.dashboard.statOrganizers': 'Organizers',
    'admin.dashboard.statRevenue': 'Revenue',
    'admin.dashboard.statVenues': 'Venues',
    'admin.dashboard.statRooms': 'Rooms',

    'admin.events.info': 'Information',
    'admin.events.logistics': 'Logistics',
    'admin.events.capacity': 'Capacity',
    'admin.events.venue': 'Venue',
    'admin.events.date': 'Date',
    'admin.events.time': 'Time',
    'admin.events.noSeatsConfigured': 'No seats configured',
    'admin.events.features': 'Features',
    'admin.events.actions': 'Actions',
    'admin.events.validate': 'Validate / Approve',
    'admin.events.validated': 'Event validated',
    'admin.events.reactivate': 'Reactivate',
    'admin.events.reactivated': 'Event reactivated',
    'admin.events.suspend': 'Suspend',
    'admin.events.suspended': 'Event suspended',
    'admin.events.cancelEvent': 'Cancel Event',
    'admin.events.cancelled': 'Event cancelled',
    'admin.events.contactOrganizer': 'Contact Organizer',
    'admin.events.cancelReason': 'Cancellation reason *',
    'admin.events.cancelReasonHint': 'Mandatory reason',
    'admin.events.contactOptions': 'Contact options:',
    'admin.events.sendEmail': 'Send an email',
    'admin.events.emailNotImplemented': 'Email feature not implemented',
    'admin.events.internalChat': 'Internal chat',
    'admin.events.openChat': 'Open chat',
    'admin.events.chatNotImplemented': 'Chat feature not implemented',
    'admin.events.empty': 'No events found',

    'admin.users.changeRole': 'Change role',
    'admin.users.roleOrganizer': 'Organizer',
    'admin.users.roleClient': 'Client',
    'admin.users.resetPassword': 'Reset password',
    'admin.users.newPassword': 'New password',
    'admin.users.newPasswordHint': 'Enter a new password',
    'admin.users.passwordReset': 'Password reset',
    'admin.users.deleteUser': 'Delete user',
    'admin.users.management': 'User management',
    'admin.users.audit': 'Audit',
    'admin.users.empty': 'No users found',
    'admin.users.active': 'Active',
    'admin.users.inactive': 'Inactive',
    'admin.users.new': 'New',
    'admin.users.role': 'Role',
    'admin.users.deactivate': 'Deactivate',
    'admin.users.activate': 'Activate',
    'admin.users.resetPwd': 'Reset PWD',
    'admin.users.noActivity': 'No activity',

    'admin.categories.add': 'Add category',
    'admin.categories.code': 'Code',
    'admin.categories.codeHint': 'CAT01',
    'admin.categories.name': 'Name',
    'admin.categories.description': 'Description',
    'admin.categories.edit': 'Edit category',
    'admin.categories.deleteTitle': 'Delete category',
    'admin.categories.deleted': 'Category deleted',
    'admin.categories.empty': 'No categories found',
    'admin.categories.features': 'Features',
    'admin.categories.rooms': 'Rooms',
    'admin.categories.config': 'Config',
    'admin.categories.addFeature': 'Add a feature',
    'admin.categories.editFeature': 'Edit feature',
    'admin.categories.dataType': 'Data type',
    'admin.categories.dataTypeText': 'Text',
    'admin.categories.dataTypeNumber': 'Number',
    'admin.categories.dataTypeDate': 'Date',
    'admin.categories.dataTypeSelect': 'Dropdown list',
    'admin.categories.dataTypeBoolean': 'Yes/No',
    'admin.categories.displayOrder': 'Display order',
    'admin.categories.options': 'Options (comma separated)',
    'admin.categories.required': 'Required',
    'admin.categories.noFeatures': 'No features',
    'admin.categories.compatibleRoomTypes': 'Compatible room types',
    'admin.categories.configSaved': 'Specific configuration saved',
    'admin.categories.cinemaConfig': 'Cinema room configuration',
    'admin.categories.numRows': 'Number of rows',
    'admin.categories.seatsPerRow': 'Seats per row',
    'admin.categories.aisles': 'Aisles (ex: B,D)',
    'admin.categories.aisleWidth': 'Aisle width',
    'admin.categories.freeSeatingZones': 'Free seating zones',
    'admin.categories.noZones': 'No zones configured',
    'admin.categories.addZone': 'Add a zone',
    'admin.categories.maxCapacity': 'Max capacity',
    'admin.categories.ticketPrice': 'Ticket price',
    'admin.categories.standsBlocks': 'Stand blocks',
    'admin.categories.noBlocks': 'No blocks configured',
    'admin.categories.addBlock': 'Add a block',
    'admin.categories.blockType': 'Type (ex: Stand A)',
    'admin.categories.numSeats': 'Number of seats',
    'admin.categories.price': 'Price',
    'admin.categories.type': 'Type',
    'admin.categories.noSpecificConfig': 'No specific configuration available for this category',

    'admin.venues.roomsFor': 'Rooms —',
    'admin.venues.noRooms': 'No rooms for this venue',
    'admin.venues.addRoom': 'Add a room',
    'admin.venues.manageSeats': 'Manage seats',
    'admin.venues.roomName': 'Room name',
    'admin.venues.venueCode': 'Venue code',
    'admin.venues.name': 'Name',
    'admin.venues.address': 'Address',
    'admin.venues.city': 'City',
    'admin.venues.empty': 'No venues found',
    'admin.venues.selectRoomType': 'Select rooms compatible with',

    'admin.places.roomDeleted': 'Room deleted',
    'admin.places.seatDeleted': 'Seat deleted',
    'admin.places.editSeat': 'Edit seat',
    'admin.places.seatNumber': 'Seat number',
    'admin.places.row': 'Row',
    'admin.places.editRoom': 'Edit room',
    'admin.places.addRoom': 'Add a room',
    'admin.places.parentVenue': 'Parent venue',
    'admin.places.roomsAndSeats': 'Rooms & Seats',
    'admin.places.searchRoom': 'Search a room...',
    'admin.places.filterByVenue': 'Filter by venue',
    'admin.places.allVenues': 'All venues',
    'admin.places.noRooms': 'No rooms found',
    'admin.places.manageSeats': 'Manage seats',
    'admin.places.multiSelect': 'Multi select',
    'admin.places.batchGeneration': 'Batch generation',
    'admin.places.rowHint': 'B',
    'admin.places.startNum': 'Start #',
    'admin.places.endNum': 'End #',
    'admin.places.generate': 'Generate',
    'admin.places.searchSeat': 'Search a seat...',
    'admin.places.noSeats': 'No seats for this room',
    'admin.places.noSeatsMatch': 'No seats match your search',
    'admin.places.deselect': 'Deselect',
    'admin.places.select': 'Select',
    'admin.places.bulkDelete': 'Bulk delete',

    'admin.tickets.empty': 'No tickets found',

    'admin.reservations.empty': 'No reservations found',

    'admin.payments.empty': 'No payments found',

    'admin.profile.personalInfo': 'Personal information',
    'admin.profile.lastName': 'Last name',
    'admin.profile.firstName': 'First name',
    'admin.profile.saveConfirm': 'Do you want to save the changes?',
    'admin.profile.updated': 'Information updated',
    'admin.profile.actionHistory': 'Action history',
    'admin.profile.logoutConfirm': 'Do you really want to log out?',

    'admin.actionHistory.undoAction': 'Undo action',
    'admin.actionHistory.yesUndo': 'Yes, undo',
    'admin.actionHistory.actionUndone': 'Action undone',
    'admin.actionHistory.createUser': 'User creation',
    'admin.actionHistory.updateUser': 'User update',
    'admin.actionHistory.changeRole': 'Role change',
    'admin.actionHistory.deactivateUser': 'User deactivation',
    'admin.actionHistory.activateUser': 'User activation',
    'admin.actionHistory.resetPassword': 'Password reset',
    'admin.actionHistory.deleteUser': 'User deletion',
    'admin.actionHistory.paymentMade': 'Payment made',
    'admin.actionHistory.refund': 'Refund',
    'admin.actionHistory.title': 'Action history',
    'admin.actionHistory.empty': 'No actions recorded',
    'admin.actionHistory.reverted': 'Reverted',
    'admin.actionHistory.undo': 'Undo',

    'notifications.title': 'Notifications',
    'notifications.empty': 'No notifications',
    'notifications.notConnected': 'User not connected',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.markAllReadShort': 'Read all',
    'notifications.filterAll': 'All',
    'notifications.filterPayments': 'Payments',
    'notifications.filterFailed': 'Failed',
    'notifications.filterReservations': 'Reservations',
    'notifications.filterCancellations': 'Cancellations',
    'notifications.filterCancelled': 'Cancelled',
    'notifications.filterApproved': 'Approved',
    'notifications.filterUpdated': 'Updated',
    'notifications.filterSuspended': 'Suspended',
    'notifications.filterScanned': 'Scanned',
    'notifications.filterReused': 'Reused',
    'notifications.filterRefunded': 'Refunded',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.read': 'Read',
    'notifications.noResults': 'No results',
    'notifications.emptyFiltered': 'No notifications match the selected filters.\nModify or reset filters to see more results.',
    'notifications.emptyGeneral': 'You will be notified here about important updates.\nBook tickets or create events to receive notifications.',
    'notifications.resetFilters': 'Reset filters',

    'pageNotFound.title': 'Page not found',
    'pageNotFound.home': 'Home',

    'widgets.error.retry': 'Retry',
    'widgets.seat_picker.row': 'Row',

    'widgets.crud.confirm': 'Confirm',
    'widgets.crud.delete_confirm': 'Delete this item?',
    'widgets.crud.cancel': 'Cancel',
    'widgets.crud.delete': 'Delete',
    'widgets.crud.bulk_delete_title': 'Bulk delete',
    'widgets.crud.bulk_delete_confirm': 'Delete {n} item(s)?',
    'widgets.crud.delete_all': 'Delete all',
    'widgets.crud.edit': 'Edit',
    'widgets.crud.add': 'Add',
    'widgets.crud.save': 'Save',
    'widgets.crud.required': 'Required',
    'widgets.crud.select_date': 'Select a date',
    'widgets.crud.select_all': 'Select all',
    'widgets.crud.delete_selection': 'Delete selection',
    'widgets.crud.exit_select_mode': 'Exit select mode',
    'widgets.crud.select_mode': 'Select mode',
    'widgets.crud.search': 'Search...',
    'widgets.crud.all': 'All',
    'widgets.crud.retry': 'Retry',
    'widgets.crud.empty': 'No items',

    'widgets.code_promo.label': 'Promo code',
    'widgets.code_promo.hint': 'Enter your promo code',
    'widgets.code_promo.apply': 'Apply',
    'widgets.code_promo.applied': 'Promo code applied!',

    'widgets.carte_bancaire.title': 'Bank card information',
    'widgets.carte_bancaire.card_number': 'Card number',
    'widgets.carte_bancaire.card_number_hint': '1234 5678 9012 3456',
    'widgets.carte_bancaire.expiry': 'Expiry date',
    'widgets.carte_bancaire.expiry_hint': 'MM/YY',
    'widgets.carte_bancaire.cvv': 'CVV',
    'widgets.carte_bancaire.cvv_hint': '123',
    'widgets.carte_bancaire.cardholder_name': 'Cardholder name',
    'widgets.carte_bancaire.cardholder_name_hint': 'JOHN DOE',

    'widgets.payment_method.title': 'Payment method',

    'widgets.two_factor.disable_2fa': 'Disable 2FA',
    'widgets.two_factor.disable_2fa_confirm': 'Are you sure you want to disable two-factor authentication?',
    'widgets.two_factor.cancel': 'Cancel',
    'widgets.two_factor.disable': 'Disable',
    'widgets.two_factor.password_2fa': 'Password & 2FA',
    'widgets.two_factor.2fa_label': 'Two-factor authentication',
    'widgets.two_factor.2fa_enabled_desc': '6-digit code sent by email',
    'widgets.two_factor.2fa_disabled_desc': 'Enable to secure your account',
    'widgets.two_factor.change_password_title': 'Change password',
    'widgets.two_factor.current_password': 'Current password',
    'widgets.two_factor.new_password': 'New password',
    'widgets.two_factor.confirm_password': 'Confirm',
    'widgets.two_factor.password_length_error': 'Password must be at least 6 characters',
    'widgets.two_factor.password_mismatch_error': 'Passwords do not match',
    'widgets.two_factor.password_changed': 'Password changed',
    'widgets.two_factor.change_password': 'Change password',
    'widgets.two_factor.activate_2fa': 'Enable 2FA',
    'widgets.two_factor.2fa_email_desc': 'A 6-digit code will be sent to your email address.',
    'widgets.two_factor.sending': 'Sending...',
    'widgets.two_factor.send_code': 'Send code',
    'widgets.two_factor.code_hint': '000000',
    'widgets.two_factor.2fa_activated': '2FA enabled',
    'widgets.two_factor.incorrect_code': 'Incorrect code',
    'widgets.two_factor.verify_activate': 'Verify & activate',

    'widgets.notification_bell.tooltip': 'Notifications',

    'widgets.profile.logout': 'Logout',
  };
}

AppLocalizations t(String locale) => AppLocalizations(locale);

String tr(String key) {
  return AppLocalizations(appLanguage).tr(key);
}
